analyzer:
  errors:
    body_might_complete_normally_catch_error: ignore
    deprecated_export_use: ignore
    deprecated_member_use: ignore
    invalid_return_type_for_catch_error: ignore
    todo: ignore
    type_check_with_null: ignore
    unnecessary_import: ignore
    unnecessary_null_comparison: ignore
    unnecessary_type_check: ignore
    unused_catch_clause: ignore
    unused_catch_stack: ignore
    unused_element: ignore
    unused_element_parameter: ignore
    unused_field: ignore
    unused_import: ignore
    unused_local_variable: ignore
    unused_shown_name: ignore
