name: expect
description: >-
  Expect is used for tests that do not want to make use of the
  Dart unit test library - for example, the core language tests.
  Third parties are discouraged from using this, and should use
  the expect() function in the unit test library instead for
  test assertions.

# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.7.1

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  lints: ^5.1.1
