name: Dart CI

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - lib/**
      - packages/**
      - test/**
      - tools/**
      - analysis_options.yaml
      - pubspec.yaml
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Analyze
        run: dart analyze --fatal-warnings .

      - name: Run Tests
        run: |
          dart tools/run_all_tests.dart
