name: Dart CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
        sdk:
          - stable
          # - dev

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install Dependencies
        run: dart pub get
        id: install

      - name: Format
        run: dart format --output=none --set-exit-if-changed .
        if: always() && steps.install.outcome == 'success'

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .
        if: always() && steps.install.outcome == 'success'

      - name: Run Tests
        run: |
          dart tools/run_all_tests.dart
        if: always() && steps.install.outcome == 'success'
